### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by sojusnik** [connervieira/Breathe#1]
Is there a manual on how to install and use this app, preferably on Ubuntu 20.10?

**Comment by connervieira** [comment]
I'm currently working on a short manual, as well as a system to make the breathing exercise automatically stop after 10 breathes, instead of going on forever.

In the meantime, to run it, simply git clone the project, and run 'main.py' with Python 3. Here's a step by step list of commands

1. git clone https://github.com/connervieira/Breathe
2. cd Breathe
3. python3 main.py
